### ISSUE TITLE
Doesn't work in (current) Git version (Yazi 0.2.5 (53d658d 2024-05-26))

### ISSUE THREAD

**Issue by angelus2014** [Reledia/glow.yazi#4]
Hello,

The plugin doesn't seem to work in the (current) Git version of Yazi (Yazi 0.2.5 (53d658d 2024-05-26)). I have both the Homebrew version (Yazi 0.2.5 (Homebrew 2024-04-23)) and the Git version on my macOS system and in the Homebrew version it works, but not in the Git version.

---
With regards,

Angelo Machils

**Comment by Reledia** [comment]
Hello, thanks for the report.

I am using the latest stable version available on pacman, so I didnt notice the error. I tried to investigate on the latest version (same as yours), but all I could find is that there is some major rework of how the mime/name association happens. I think for the moment, the best solution is to wait for the author to publish the migration guide to yazi 3.0 (https://github.com/sxyazi/yazi/issues/1046)

**Comment by angelus2014** [comment]
Sounds good!

**Comment by Reledia** [comment]
Tried the latest git version, it seems to work now. If you too can confirm @angelus2014 I will close the issue

**Comment by angelus2014** [comment]
Yup, it works in Git version: Yazi 0.2.5 (46cd42f 2024-05-27)

Thank you!
