### ISSUE TITLE
Previews no longer working with `glow` 2.0.0

### ISSUE THREAD

**Issue by xfzv** [Reledia/glow.yazi#7]
[glow 2.0.0 was released on 2024-08-23](https://github.com/charmbracelet/glow/releases/tag/v2.0.0).

On my Gentoo install with `glow` 1.5.1, `glow.yazi` displays markdown previews just fine.

However, on my two Arch Linux installs with `glow` 2.0.0, all I'm getting is regular text.

Downgrading to 1.5.1 on Arch Linux solves the issue.

---

Edit: Also broken on my Gentoo install after updating `glow` to 2.0.0.

**Comment by Reledia** [comment]
By https://github.com/charmbracelet/glow/issues/440, you need to set the env variable `CLICOLOR_FORCE` to 1. It is a workaround, but there is no other mention of this since v2.0 that I can find.

**Comment by wiraki** [comment]
There is this pull request: https://github.com/Reledia/glow.yazi/pull/8

You can check the change it makes in `init.lua` in the commits and manually make the same change yourself in `~/.config/yazi/plugins/glow.yazi/init.lua`

**Comment by Reledia** [comment]
Merged it
