### ISSUE TITLE
Broken after upstream change (`ui.Paragraph` removed)

### ISSUE THREAD

**Issue by xfzv** [Reledia/glow.yazi#9]
After updating to https://github.com/sxyazi/yazi/commit/43b5ae0e6cc5c8ee96462651f01d78a0d98077fc, `glow.yazi` stopped working.

ref: https://github.com/sxyazi/yazi/pull/1776

---

This fixes the issue:

https://github.com/Reledia/glow.yazi/blob/d8b36ff0113e73a400891726dc2eca8b3c049dea/init.lua#L45

```diff
- ya.preview_widgets(self, { ui.Paragraph.parse(self.area, lines) })
+ ya.preview_widgets(self, { ui.Text.parse(lines):area(self.area) })
```

Not sure about this though:

https://github.com/Reledia/glow.yazi/blob/d8b36ff0113e73a400891726dc2eca8b3c049dea/init.lua#L65-L67

This maybe?

```diff
- ya.preview_widgets(self, {
-  ui.Paragraph(self.area, { ui.Line(err):reverse() }),
- })

+ ya.preview_widgets(self, {
+  ui.Text({ ui.Line(err):reverse() }):area(self.area),
+ })
```

**Comment by Reledia** [comment]
Merged

**Comment by Reledia** [comment]
> > Merged
> 
> Sorry but it's not? #10

I had a problem of being very stupid, corrected
